### ISSUE TITLE
spark jar file

### ISSUE THREAD

**Issue by Arnold1** [liyinan926/spark-operator#2]
Hi,

Where can i find spark-examples_2.11-2.2.0-k8s-0.5.0.jar?

and how can i stark spark on k8s using minicube? I want to run spark-examples_2.11-2.2.0-k8s-0.5.0.jar

Im on osx...

Thanks,
Arnold

**Comment by liyinan926** [comment]
The example jar can be found in the driver and executor image kubespark/spark-driver:v2.2.0-k8s-0.5.0 and kubespark/spark-executor:v2.2.0-k8s-0.5.0.

**Comment by liyinan926** [comment]
> and how can i stark spark on k8s using minicube? I want to run spark-examples_2.11-2.2.0-k8s-0.5.0.jar

Do you mean how to use spark-operator to run the example? You can also submit applications directly without using spark-operator, see https://github.com/apache-spark-on-k8s/userdocs/blob/master/src/jekyll/running-on-kubernetes.md.

**Comment by Arnold1** [comment]
Yeah.

I tried to run it as documented (cloned the spark repo - https://github.com/apache-spark-on-k8s/userdocs/blob/master/src/jekyll/running-on-kubernetes.md. into the following dir) but got an error...
```
$ pwd
/Users/arnold/run_spark_on_k8s
$ ls
run.sh		spark

$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

my run.sh file:
```
k8s_apiserver_host="192.168.99.100"
k8s_apiserver_port="8443"
cwd=`pwd`

echo $k8s_apiserver_host
echo $k8s_apiserver_port
echo $cwd

spark/bin/spark-submit \
  --deploy-mode cluster \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://https://$k8s_apiserver_host:$k8s_apiserver_port \
  --kubernetes-namespace default \
  --conf spark.executor.instances=5 \
  --conf spark.app.name=spark-pi \
  --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  local:///$cwd/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

running the run.sh file:
```
$ ./run.sh 
192.168.99.100
8443
/Users/arnold/run_spark_on_k8s
java.lang.ClassNotFoundException: org.apache.spark.deploy.k8s.submit.Client
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:230)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

jar file is available here:
```
$ ls -la /Users/arnold/run_spark_on_k8s/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
-rw-r--r--  1 arnold  1113146471  1991195 Dec 22 14:21 /Users/arnold/run_spark_on_k8s/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```
any idea about the java.lang.ClassNotFoundException?

**Comment by liyinan926** [comment]
It doesn't seem you were using spark-operator to run your spark job. So this repo is the right place to file issue. Please file future issues at https://github.com/apache-spark-on-k8s/spark/issues. 

Regarding this issue, the `local://` scheme is for files in the Docker containers. In this particular case, the example jar is located at `local:///opt/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar`.

**Comment by Arnold1** [comment]
@liyinan926 i want to make sure i get the default example to run before using spark-operator.

if i use:
```local:///opt/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar```
i get the same error:
```
java.lang.ClassNotFoundException: org.apache.spark.deploy.k8s.submit.Client
```

**Comment by liyinan926** [comment]
Are you using the release distribution to submit your application?

**Comment by Arnold1** [comment]
@liyinan926 here is what i did:
```
git clone https://github.com/apache-spark-on-k8s/spark
cd spark
build/mvn -DskipTests clean package # according to here: https://github.com/apache-spark-on-k8s/spark
minikube start
./run.sh
```

should i clone a different repo?

**Comment by Arnold1** [comment]
i think i figured out the reason, is the documentation wrong?
i rebuilt spark with this command:
```
dev/make-distribution.sh --tgz -Phadoop-2.7 -Pkubernetes # build Spark against Hadoop 2.7 and Kubernetes
```

starting my run.sh script i get the following output, it starts spark-pi but fails...?
```
$ ./run.sh 
192.168.99.100
8443
/Users/arnold/run_spark_on_k8s
2017-12-27 11:03:25 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514390604305-driver
	 namespace: default
	 labels: spark-app-selector -> spark-edaa140665af4c208b81c7c4e0e45cbb, spark-role -> driver
	 pod uid: 78465ecb-eb1f-11e7-9c13-08002718fe97
	 creation time: 2017-12-27T16:03:25Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-8f3cd8c4-2c29-48ca-b4e0-da39e60e5207, default-token-nxcnb
	 node name: N/A
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
2017-12-27 11:03:25 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514390604305-driver
	 namespace: default
	 labels: spark-app-selector -> spark-edaa140665af4c208b81c7c4e0e45cbb, spark-role -> driver
	 pod uid: 78465ecb-eb1f-11e7-9c13-08002718fe97
	 creation time: 2017-12-27T16:03:25Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-8f3cd8c4-2c29-48ca-b4e0-da39e60e5207, default-token-nxcnb
	 node name: minikube
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
2017-12-27 11:03:25 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514390604305-driver
	 namespace: default
	 labels: spark-app-selector -> spark-edaa140665af4c208b81c7c4e0e45cbb, spark-role -> driver
	 pod uid: 78465ecb-eb1f-11e7-9c13-08002718fe97
	 creation time: 2017-12-27T16:03:25Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-8f3cd8c4-2c29-48ca-b4e0-da39e60e5207, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-27T16:03:25Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=ContainerCreating, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-12-27 11:03:25 INFO  Client:54 - Waiting for application spark-pi to finish...
2017-12-27 11:03:52 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514390604305-driver
	 namespace: default
	 labels: spark-app-selector -> spark-edaa140665af4c208b81c7c4e0e45cbb, spark-role -> driver
	 pod uid: 78465ecb-eb1f-11e7-9c13-08002718fe97
	 creation time: 2017-12-27T16:03:25Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-8f3cd8c4-2c29-48ca-b4e0-da39e60e5207, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-27T16:03:25Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Failed
	 status: [ContainerStatus(containerID=docker://3e32e5a4d0fa2e2abfee0c5ae51bcb13949693b7d4bf5e07f284c35d45fe0b7f, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=docker-pullable://kubespark/spark-driver@sha256:7539c28c4dbfc55addf5c3f439d26b964c4b04cd780a066c708242867356eb0b, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://3e32e5a4d0fa2e2abfee0c5ae51bcb13949693b7d4bf5e07f284c35d45fe0b7f, exitCode=1, finishedAt=Time(time=2017-12-27T16:03:52Z, additionalProperties={}), message=null, reason=Error, signal=null, startedAt=Time(time=2017-12-27T16:03:51Z, additionalProperties={}), additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})]
2017-12-27 11:03:52 INFO  LoggingPodStatusWatcherImpl:54 - Container final statuses:


	 Container name: spark-kubernetes-driver
	 Container image: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 Container state: Terminated
	 Exit code: 1
2017-12-27 11:03:52 INFO  Client:54 - Application spark-pi finished.
```

run.sh script:
```
k8s_apiserver_host="192.168.99.100"
k8s_apiserver_port="8443"
cwd=`pwd`

echo $k8s_apiserver_host
echo $k8s_apiserver_port
echo $cwd

spark/bin/spark-submit \
  --deploy-mode cluster \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://https://$k8s_apiserver_host:$k8s_apiserver_port \
  --kubernetes-namespace default \
  --conf spark.executor.instances=5 \
  --conf spark.app.name=spark-pi \
  --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  local:///opt/spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

**Comment by liyinan926** [comment]
Yes, you need to use a pre-built release distribution or make your own distribution to submit applications.

**Comment by Arnold1** [comment]
hm, what did i forget to install? could you point me to a pre-built release distribution and how to make your own distribution?
